# -*- coding:utf-8 -*-
class weatherModel:
    id = ''
    overview = ''
    province = ''
    county = ''
    temperature = ''
    weather_condition = ''
    humidity = ''
    wind_direction = ''
    msg_update_time = ''
    create_date = ''
    pm25 = ''
    warning = ''
    makeup = ''
    cold = ''
    car_wash = ''
    air_pollution = ''
    dress = ''
    ultraviolet_rays = ''
    sport = ''
    go_fishing = ''
